### ISSUE TITLE
Indices of annular modes

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#14]
This is a tracking issue for the final integration of *Indices of annular modes metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Tasks:**
----------

**ESMValTool** 
- [x] Metric working standalone
- [x] Recipe created in ESMValTool branch
- [x] Pull request created
- [x] Runs on Jasmin with CP4CDS and DLR OBS
- [x] Read The Docs page complete
- [x] Provenance-enabled
- [x] Merged to ESMValTool development branch
- [ ] Works with entire CP4CDS dataset (tested by partners)
- [ ] ESMValTool development done
- [ ] In ESMValTool alfa/beta/gamma release

**WPS process**
- [ ] WPS Process working on development infra
- [ ] WPS Process settings completed
- [ ] In MAGIC WPS release
- [ ] WPS Process working on CP4CDS infra

**Portal**
- [ ] Precalculated data automatically run on Jasmin
- [ ] Diagnostic page on portal complete
- [ ] In MAGIC portal release

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/annularmodes)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_zmnam.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@jhardenberg

**Comment by jhardenberg** [comment]
This is a duplicate of https://github.com/c3s-magic/c3s-magic-metric-status/issues/6
As discussed with Niels, we could merge these two

**Comment by yifatdzigan** [comment]
Will be merged with #6

**Comment by nielsdrost** [comment]
@jhardenberg , yes we will have a single ESMValTool metric and WPS process. Would it still make sense to have two portal pages, or would you rather also merge these?

**Comment by jhardenberg** [comment]
In my opinion we could actually merge also the portal pages. We can then say that this product fulfilled both requests from the project (as it does) ....

**Comment by yifatdzigan** [comment]
Merging this metric with #6

**Comment by nielsdrost** [comment]
see https://github.com/c3s-magic/c3s-magic-frontend/pull/216
