### ISSUE TITLE
Weather regimes

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#16]
This is a tracking issue for the final integration of *Weather regimes metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Tasks:**
----------

**ESMValTool** 
- [x] Metric working standalone
- [x] Recipe created in ESMValTool branch
- [x] Pull request created
- [x] Runs on Jasmin with CP4CDS and DLR OBS
- [x] Read The Docs page complete
- [x] Provenance-enabled
- [x] Merged to ESMValTool development branch
- [ ] Works with entire CP4CDS dataset (tested by partners)
- [x] ESMValTool development done
- [ ] In ESMValTool alfa/beta/gamma release

**WPS process**
- [x] WPS Process working on development infra
- [ ] WPS Process settings completed
   - [ ] Reference Models
- [ ] In MAGIC WPS release
- [ ] WPS Process working on CP4CDS infra

**Portal**
- [ ] Precalculated data automatically run on Jasmin
- [ ] Diagnostic page on portal complete
- [ ] In MAGIC portal release

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/teleconnections)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_miles_regimes.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@jhardenberg
@earnone

**Comment by yifatdzigan** [comment]
@bpmweel Recipe works. Ready for WPS integration

**Comment by jhardenberg** [comment]
I tested it on the portal and it seems to be failing (something with the ERA-Interim reference dataset)

**Comment by bpmweel** [comment]
@jhardenberg Could you please try again, for it works now. Do you have any other comments besides the reference model and model choice list as mentioned in the other issues?

**Comment by earnone** [comment]
@bpmweel I am afraid this is not working with default settings or other models, it does not find the model data.

**Comment by jhardenberg** [comment]
- The default model suggested is ACCESS1-0 r2i1p1. Unfortunately r2i1p1 of ACCESS1-0 does not have the geopotential zg variable needed for this diagnostic. ACCESS1-0 r1i1p1 instead does have the right variable. Is there a way to exclude r2i1p1 for ACCESS1-0 from the selection?
The same problem applies to teleconnections https://github.com/c3s-magic/c3s-magic-metric-status/issues/15 and blocking  https://github.com/c3s-magic/c3s-magic-metric-status/issues/5
- If I select two models (using the little + button) a recipe mentioning only the first model selected is created and the diagnostic works only for the first model. I noticed the same problem also for 
 teleconnections #15 and blocking #5

**Comment by earnone** [comment]
This is working well with correct settings. See comment by @jhardenberg still valid.

**Comment by jhardenberg** [comment]
I tested the calculate page. It is still not possible to change the years.
The recipe computes 4 weather regime patterns, but the “Regime data” panel only shows one of them  (confusingly the last one)

**Comment by jhardenberg** [comment]
Issues in the landing page of this metric:

In "Settings" It says that the "Variable" is geopotential height, but it should specify that it is at 500hPa (Z500)

**Comment by rvanharen** [comment]
@jhardenberg @earnone the 'plus' sign to add more models will not show up anymore apart for the metrics that we know we can throw multiple models at.

**Comment by jhardenberg** [comment]
Thanks for fixing the other issues. I just tried on portal.c3s-magic.eu and one problem mentioned above still remains: In the interactive "Regime data" there is only one layer, corresponding to the 4th regime. There should be 4 layers here, corresponding to the 4 regimes computed by the diagnostics. 
A typical output file such as RegimesPattern_ACCESS1-0_historical_r1i1p1_1984-1989_DJF.nc  has a variable "Regimes" with 4 levels. It is these 4 levels which we should be plotting (corresponding to the 4 regimes computed by the diagnostic)

**Comment by jhardenberg** [comment]
After getting feedback from a coauthor, we updated the description of the diagnostic in the landing page (diagnostics & metrics). I prepared directly a PR, which you just need to accept:
https://github.com/c3s-magic/c3s-magic-frontend/pull/253
