### ISSUE TITLE
Correlations

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#18]
This is a tracking issue for the final integration of *Correlations metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Tasks:**
----------

**ESMValTool** 
- [x] Metric working standalone
- [ ] Recipe created in ESMValTool branch
- [ ] Pull request created
- [ ] Runs on Jasmin with CP4CDS and DLR OBS
- [ ] Read The Docs page complete
- [ ] Provenance-enabled
- [ ] Merged to ESMValTool development branch
- [ ] Works with entire CP4CDS dataset (tested by partners)
- [ ] ESMValTool development done
- [ ] In ESMValTool alfa/beta/gamma release

**WPS process**
- [ ] WPS Process working on development infra
- [ ] WPS Process settings completed
- [ ] In MAGIC WPS release
- [ ] WPS Process working on CP4CDS infra

**Portal**
- [ ] Precalculated data automatically run on Jasmin
- [ ] Diagnostic page on portal complete
- [ ] In MAGIC portal release

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/correlations)
Recipe does not exist yet
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@maartenplieger
