### ISSUE TITLE
Toy model 

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#28]
This is a tracking issue for the final integration of *Toy model metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Tasks:**
----------

**ESMValTool** 
- [x] Metric working standalone
- [x] Recipe created in ESMValTool branch
- [x] Pull request created
- [x] Runs on Jasmin with CP4CDS and DLR OBS
- [x] Read The Docs page complete
- [x] Provenance-enabled
- [x] Merged to ESMValTool development branch
- [ ] Works with entire CP4CDS dataset (tested by partners)
- [x] ESMValTool development done
- [ ] In ESMValTool alfa/beta/gamma release

**WPS process**
- [x] WPS Process working on development infra
- [ ] WPS Process settings completed
- [ ] In MAGIC WPS release
- [ ] WPS Process working on CP4CDS infra

**Portal**
- [ ] Precalculated data automatically run on Jasmin
- [ ] Diagnostic page on portal complete
- [ ] In MAGIC portal release

**Links:**
----------

[Portal]: does not exist yet
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_toymodel.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@nperezzanon

**Comment by yifatdzigan** [comment]
@bpmweel Recipe works. Ready for WPS integration

**Comment by yifatdzigan** [comment]
@yifatdzigan we should create a portal webpage

**Comment by nielsdrost** [comment]
Portal page created by @nperezzanon  in this pull request to the frontend: https://github.com/c3s-magic/c3s-magic-frontend/pull/211

**Comment by bpmweel** [comment]
First implementation on wps is done.

@nperezzanon Could you have a look at https://portal-dev.c3s-magic.eu/#/calculate/copernicus-wps/toymodel whether you have any feedback. If not we will consider it completed for the wps.

**Comment by nperezzanon** [comment]
Hi,
All settings are being displayed but I cannot modify them. 
The automatic map is not displaying any data. 
There is not a box for this recipe in the tab Metrics&Diagnostics.
Núria

**Comment by nperezzanon** [comment]
The variable cannot be selected.

**Comment by bpmweel** [comment]
@nperezzanon could you let me know which variables this metric is capable of running with? The documentation only mentions psl.

**Comment by nperezzanon** [comment]
Hi,
This recipe should work with any atmospheric variable with gaussian distribution, I have corrected the documentation and created a merge request to include variable 'tas'.
Thanks for your help

**Comment by bpmweel** [comment]
@nperezzanon Are there any other ones you would like to include beyond psl and tas?

**Comment by nperezzanon** [comment]
No

**Comment by lpcaron** [comment]
The recipe doesn't run currently.

**Comment by lpcaron** [comment]
Also, this recipe is aimed to be applied to observations, not model output.

**Comment by nielsdrost** [comment]
> Also, this recipe is aimed to be applied to observations, not model output.

The WPS follows the recipe, which uses model data: https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_toymodel.yml

Perhaps @nperezzanon can comment?

For now, we are leaving it as is.

**Comment by yifatdzigan** [comment]
File doesn't work on ADAGUC
