### ISSUE TITLE
SMPI - Single Model Performance Index

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#4]
This is a tracking issue for the final integration of *smpi metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Tasks:**
----------

**ESMValTool** 
- [x] Metric working standalone
- [x] Recipe created in ESMValTool branch
- [x] Pull request created
- [ ] Runs on Jasmin with CP4CDS and DLR OBS
- [ ] Read The Docs page complete
- [X] Provenance-enabled
- [x] Merged to ESMValTool development branch
- [ ] Works with entire CP4CDS dataset (tested by partners)
- [ ] ESMValTool development done
- [ ] In ESMValTool alfa/beta/gamma release

**WPS process**
- [ ] WPS Process working on development infra
- [ ] WPS Process settings completed
- [ ] In MAGIC WPS release
- [ ] WPS Process working on CP4CDS infra

**Portal**
- [ ] Precalculated data automatically run on Jasmin
- [ ] Diagnostic page on portal complete
- [ ] In MAGIC portal release

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/smpi)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_smpi.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@mattiarighi

**Comment by yifatdzigan** [comment]
@mattiarighi 
Could you please provide a link to the recipe yml file?

**Comment by mattiarighi** [comment]
See [here](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_smpi.yml).

**Comment by yifatdzigan** [comment]
@bpmweel metric tested on DAS5 and ready for integration on WPS (new metric)

**Comment by bpmweel** [comment]
@mattiarighi I'm working on the wps process for this recipe and I have a few questions:

1. In the recipe there are multiple models, does the recipe require this or can it run with 1 model as well. Does it provide more outputs if there are more models?
2. For the setting plot_type: some in the recipe are cycle_zonal, some are cycle_latlon. Are these 2 groups of plot_type metrics, or could a user want them all to be the same? Having fewer plot types to set in the frontend would be preferable.
3. time_avg: The documentation of esmvaltool says the valid values are montlyclim, seasonalclim, annualclim, however the recipe uses the value yearly, what are the correct valid values?


@bouweandela @nielsdrost This recipe uses multiple reference datasets in the additional_dataset section, we should make sure these are available on the wps server.

**Comment by hb326** [comment]
> 
> 
> @mattiarighi I'm working on the wps process for this recipe and I have a few questions:
> 
>     1. In the recipe there are multiple models, does the recipe require this or can it run with 1 model as well. Does it provide more outputs if there are more models?
> 
>     2. For the setting plot_type: some in the recipe are cycle_zonal, some are cycle_latlon. Are these 2 groups of plot_type metrics, or could a user want them all to be the same? Having fewer plot types to set in the frontend would be preferable.
> 
>     3. time_avg: The documentation of esmvaltool says the valid values are montlyclim, seasonalclim, annualclim, however the recipe uses the value yearly, what are the correct valid values?
> 

@bpmweel:
1. The recipe does need at least 2 models to run properly. It calculates a multi-model-mean that cannot be calculated if only one model is available. The output is always only one plot, but the number of circles on the plot depends on the number of models used. 
2. The plot type is determined by the format of the variable that is processed: as a rule of thumb, for 2D variables (e.g. tas) the plot type "cycle_latlon" is used, for 3D variables (e.g. ua) the plot type "cycle_zonal" is used. We basically used the same variables (2D or 3D) as were given in the reference.
3. The valid value is "yearly". We have adjusted the documentation for the smpi recipe and this should be merged soon now (see pull request #1088)

Hope this clarifies things!

**Comment by bouweandela** [comment]
> 2. The plot type is determined by the format of the variable that is processed: as a rule of thumb, for 2D variables (e.g. tas) the plot type "cycle_latlon" is used, for 3D variables (e.g. ua) the plot type "cycle_zonal" is used. We basically used the same variables (2D or 3D) as were given in the reference.

this means it cannot be configured. I think only model selection is needed for this recipe, none of the options appear to be changeable.
