### ISSUE TITLE
ZMNAM - Stratosphere troposphere coupling and annular modes indices 

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#6]
This is a tracking issue for the final integration of *Stratosphere troposphere coupling metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Tasks:**
----------

**ESMValTool** 
- [x] Metric working standalone
- [x] Recipe created in ESMValTool branch
- [x] Pull request created
- [x] Runs on Jasmin with CP4CDS and DLR OBS
- [x] Read The Docs page complete
- [x] Provenance-enabled
- [x] Merged to ESMValTool development branch
- [ ] Works with entire CP4CDS dataset (tested by partners)
- [x] ESMValTool development done
- [ ] In ESMValTool alfa/beta/gamma release

**WPS process**
- [x] WPS Process working on development infra
- [ ] WPS Process settings completed
- [ ] In MAGIC WPS release
- [ ] WPS Process working on CP4CDS infra

**Portal**
- [ ] Precalculated data automatically run on Jasmin
- [ ] Diagnostic page on portal complete
- [ ] In MAGIC portal release

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/stratosphere-troposphere)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_zmnam.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@jhardenberg

**Comment by jhardenberg** [comment]
Thank you for opening this issue:
Problems I can see at the moment with the portal (in portal-dev) for this diagnostic:
1) only one model (dataset) can be selected
2) only the "amip" exp can be selected. Should this not allow also historical, rcp45 etc?
3) The rip selection should ideally be guided, i.e. non all rips are available for all models, how do you solve that?
4) the left column says "model" for all three selections above (should these not be named for example "dataset (or model)", "experiment", "ensemble" ?

What happens if a user wishes to compute the statistic across 2005? I.e. if I select RCP45 will there be an assumption that "historical" is used before 2005 ? (ESMValTool allows for selecting years across more than one experiment in the recipe)

Some of these issues are common also to other diagnostics, I will not repeat them for simplicity, but we should check them all.

**Comment by nielsdrost** [comment]
Thanks for the feedback!

Yes, all options should be available in the WPS (and thus appear in the portal). We're working on that now. Unfortunately dependencies between options (such as limiting possible year range when selecting an experiment) are not something WPS supports. We may be able to add some support in the portal, but it won't help for using the WPS from the CDS, since they can rely on WPS only.

**Comment by yifatdzigan** [comment]
@yifatdzigan I am working on the portal front page to combine ZMNAM into 1 portal page

**Comment by jhardenberg** [comment]
Still failing ....

**Comment by earnone** [comment]
Failing because it does not find the model data. Maybe default end year could be 2005 to avoid concatenation if that does not work.

**Comment by jhardenberg** [comment]
Issues for the landing page of this metric:
1) Federico Serva is appearing twice in the authors list. Enrico Arnone (ISAC-CNR) is missing instead.
2) In the "Metric Results" interactive plots, the plots
    - Daily zonal mean
   - Monthly zonal mean
   - Zonal mean annual 
  do not plot correctly, since they are zonal means and are plotted as lon-lat maps instead.
3) Still in "Metric results" the pngdata files are plotted on a lon-lat plot, but are instead polar plots which should be plotted centered on the pole.
  Actually, we suggest to remove these figures from the intearctive plot and to add them at the bottom together with the other example figures.
