### ISSUE TITLE
Assessment of climate variability and teleconnections

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#7]
This is a tracking issue for the final integration of *Assessment of climate variability and teleconnections metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Tasks:**
----------

**ESMValTool** 
- [x] Metric working standalone
- [x] Recipe created in ESMValTool branch
- [x] Pull request created
- [x] Runs on Jasmin with CP4CDS and DLR OBS
- [x] Read The Docs page complete
- [x] Provenance-enabled
- [x] Merged to ESMValTool development branch
- [ ] Works with entire CP4CDS dataset (tested by partners)
- [ ] ESMValTool development done
- [ ] In ESMValTool alfa/beta/gamma release

**WPS process**
- [ ] WPS Process working on development infra
- [ ] WPS Process settings completed
- [ ] In MAGIC WPS release
- [ ] WPS Process working on CP4CDS infra

**Portal**
- [ ] Precalculated data automatically run on Jasmin
- [ ] Diagnostic page on portal complete
- [ ] In MAGIC portal release

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/modes_of_variability)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_modes_of_variability.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@alasdairhunter 
@nmanuben 
@nperezzanon

**Comment by yifatdzigan** [comment]
@bpmweel Recipe works. Ready for WPS integration

**Comment by yifatdzigan** [comment]
@nperezzanon Are you still working on this metric? Did you test it on the CP4CDS datasets?

**Comment by nperezzanon** [comment]
Hi,
I am not working now in this recipe. I checked the recipe_modes_of_varibaility on the CP4CDS.

**Comment by yifatdzigan** [comment]
file doesn't work in ADAGUC

**Comment by lpcaron** [comment]
The function in missing min/max of latitudes and longitudes.

**Comment by lpcaron** [comment]
Also, the plots are the same for the model and the observations.
