### ISSUE TITLE
Hydroclimatic intensity (HyInt) and extremes

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#8]
This is a tracking issue for the final integration of *Hydroclimatic intensity (HyInt) and extremes metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Tasks:**
----------

**ESMValTool** 
- [x] Metric working standalone
- [x] Recipe created in ESMValTool branch
- [x] Pull request created
- [ ] Runs on Jasmin with CP4CDS and DLR OBS
- [ ] Read The Docs page complete
- [ ] Provenance-enabled
- [ ] Merged to ESMValTool development branch
- [ ] Works with entire CP4CDS dataset (tested by partners)
- [ ] ESMValTool development done
- [ ] In ESMValTool alfa/beta/gamma release

**WPS process**
- [ ] WPS Process working on development infra
- [ ] WPS Process settings completed
- [ ] In MAGIC WPS release
- [ ] WPS Process working on CP4CDS infra

**Portal**
- [ ] Precalculated data automatically run on Jasmin
- [ ] Diagnostic page on portal complete
- [ ] In MAGIC portal release

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/hyint)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/REFACTORING_hyint/esmvaltool/recipes/recipe_hyint.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@jhardenberg 
@earnone

**Comment by nielsdrost** [comment]
Work being done on integrating this metric into ESMValTool here: https://github.com/ESMValGroup/ESMValTool/pull/754

**Comment by earnone** [comment]
This is now merged in `version2_development`. It includes documentation, provenance also for figures, was tested on 25 models, runs on Jasmin. See [https://github.com/ESMValGroup/ESMValTool/pull/754](https://github.com/ESMValGroup/ESMValTool/pull/754)

**Comment by earnone** [comment]
Hyint and Hyint_trends+significance_testing should now be unified as one tool  also in the portal. How do we proceed?

**Comment by yifatdzigan** [comment]
I am currently working on the portal page.

**Comment by yifatdzigan** [comment]
@earnone I have created a new portal page to represent the merged hyint metrics and the new settings you use. I also updated the description according to https://esmvaltool.readthedocs.io/en/version2_development/recipes/recipe_hyint.html.
In the readthedocs you mention a third reference: Alexander, 2016, without any further information. Is this the paper: https://doi.org/10.1016/j.wace.2015.10.007 ? If not, could you provide the correct link?
Could you also update this in the readthedocs?

**Comment by earnone** [comment]
@yifatdzigan thanks for the merged page. Where can I find it and comment on it if needed it? Would you please remove the Alexander 2016 reference. References to ETCCDI indices can be found through the climdex website as included in the description. I will update the readthedocs.

**Comment by yifatdzigan** [comment]
@earnone You can find the merged page in: https://github.com/c3s-magic/c3s-magic-frontend/tree/master/src/static/diagnosticsdata/hyint .
You can use the instructions in: https://github.com/c3s-magic/c3s-magic-frontend to run a local updated version on your computer, or otherwise see the description file.
I would appreciate your comments on the page!

**Comment by earnone** [comment]
@yifatdzigan many thanks for this. I think this looks good, I will have some refinements to propose but that depends also on whether the interactive map with pre-compiled data will still be included or not. Is that the case? Are the settings reported in the portal page of the diagnostics those that will be available once the calculation page is open? I could not run the docker but will update the text.

**Comment by yifatdzigan** [comment]
@earnone with pleasure! The reported settings are the ones used for the specific example/s in the diagnostic' page. You will be able to choose other settings in the calculation page. 
We still need to run the diagnostics on Jasmin for the outputs so I am not sure about the interactive map yet, but I think it will be included.

**Comment by jhardenberg** [comment]
Issues in the landing page of this diagnostic:
- In the "Metric results" interactive plots, when we select a layer, some layer names cannot be read correctly (some of them are so long that they are pushig the others outside of the window that can be seen) 
Solution, use only the first part of the layer description. Example:
Instead of "Annual mean dry spell length from hyint_ACCESS1-0_historical_r1i1p1_1990_2005_ALL.nc" use only 
"Annual mean dry spell length"

**Comment by earnone** [comment]
@JaroCamphuijsen @rvanharen thanks for adding the calculation for hyint. It is currently not working but I have several comments if I can give them on the current version. I cannot understand where it fails. 

E.g.: 
- it would be good to have a reference model rather than a reference dataset since it works on projections. Maybe give ACCESS1-0 as a default.
- the years cannot be selected. If they were, we could have a very quick calculation on a few years for the demo.
- all available regions should be included in the list:  (see the original recipe) and more importantly the user should be able to select more than one region (see multi-region figures plot_type 12 and 14). The full list with codes to be passed to the diagnostic is the following one, and in the menu it would be better to have the full name of each region: GL=Globe, GL60=Globe 60S/60N, TR=Tropics (30S/30N), SA=South America, AF =Africa,6NA=North America, IN=India, EU=Europe, EA=East-Asia, AU=Australia
-  also it should be possible to select multiple indices since many figures work on multiple panels, one for each index

**Comment by earnone** [comment]
@yifatdzigan could you please update the "Description" on the portal page as follows:
The HyInt metrics calculates the HY-INT hydroclimatic intensity and additional hydroclimatic indices, which allow to evaluate the overall behaviour of the hydroclimatic cycle. It produces maps, timeseries, trends and significant testing for the selected hydroclimatic indices, and can also include data from the ETCCDI indices of extremes for a joint analysis.

**Comment by rvanharen** [comment]
> @JaroCamphuijsen @rvanharen thanks for adding the calculation for hyint. It is currently not working but I have several comments if I can give them on the current version. I cannot understand where it fails.
> 
> E.g.:
> 
>     * it would be good to have a reference model rather than a reference dataset since it works on projections. Maybe give ACCESS1-0 as a default.
> 
>     * the years cannot be selected. If they were, we could have a very quick calculation on a few years for the demo.
> 
>     * all available regions should be included in the list:  (see the original recipe) and more importantly the user should be able to select more than one region (see multi-region figures plot_type 12 and 14). The full list with codes to be passed to the diagnostic is the following one, and in the menu it would be better to have the full name of each region: GL=Globe, GL60=Globe 60S/60N, TR=Tropics (30S/30N), SA=South America, AF =Africa,6NA=North America, IN=India, EU=Europe, EA=East-Asia, AU=Australia
> 
>     * also it should be possible to select multiple indices since many figures work on multiple panels, one for each index

- I'll push a fix for the reference model instead of a reference dataset
- Non-selectable years is a known bug in the frontend that was introduced late last week, we'll make sure it will be fixed.
- I'll recheck the regions and add missing ones. The pywps LiteralInput we use doesn't have support for using a different name for the text. It may be possible by defining ComplexInputs but I don't think we will have time for it before the demo.
 -This is a limitation of the frontend. I don't think @maartenplieger got around implementing multi-selection. The only hacky way this currently could work is if we define a textbox where the user needs to type a list of all options which is not very user friendly and error prone. Ideally we would like to support it, but for now I think it is best if the user just re-runs the metric for a different region/metric.

**Comment by earnone** [comment]
I see, ok. For future development beside the demo, the wps itself will in any case be able to handle multiple indices and regions at the same time, right?

**Comment by rvanharen** [comment]
@earnone yes that should work. The only thing that needs adding is some keyword telling which options are multi-selectable and which are not.

**Comment by earnone** [comment]
@rvanharen good, these are reported as example/default settings in the recipe (not exhaustive of all possibilities):
*         select_indices: ["pa_norm", "hyint", "int_norm", "r95_norm", "wsl_norm", "dsl_norm"]
*         select_regions: ["GL", "SA", "AF", "EU", "EA"]
*         plot_type: [1, 2, 3, 12, 13, 14, 15]

**Comment by rvanharen** [comment]
@earnone we hardcoded the plot_type to always plot all in order to keep it simple for the user. Is this okay for now? (else we again would get into the dropdown menu thing without multi-selection)

**Comment by jhardenberg** [comment]
HyINT is missing a "calculate" logo in the Metrics & Diagnostics page https://portal.c3s-magic.eu/#/diagnostics and a "calculate" button in the corresponding landing page (checked on portal.c3s-magic.eu)

**Comment by earnone** [comment]
@rvanharen the "calculate" works, great. There are a few issues that lead to errors/crashes:

- the default normalization period should be within the start to end year period. You can keep as default what it was before (1980-2020 start to end, 1980-1999 normalization period) or have it short for testing (say 2005-2008 start to end, 2005-2006 for normalization).

- if a user selects "historical" and then start-end year 2005-2008, the process hangs with no comments. See e.g. [here](https://portal.c3s-magic.eu/wps/outputs/afa1ad30-86b9-11e9-89e5-0242ac160008.xml)

- output plots are not automatically displayed and one needs to download the whole archive to see them

**Comment by jhardenberg** [comment]
The note says "Note: Selected models should be experiment (eg. "rcp85") and not historical. The historical data will be added automatically. " 
@earnone  does this mean that only rcp85 (or rcp45) should be selected? 
Why? The ESMValTool docs do not describe this limitation.
If true, then "historical" should be removed from the model experiment dropdown list.

**Comment by earnone** [comment]
@jhardenberg @rvanharen no, the recipe correctly calls the preproc with concatenation so it can handle only historical or historical+rcp. I guess this means that you should select rcp85 if you want both historical+rcp85. Currently it does not work so I cannot test the historical alone.

**Comment by bpmweel** [comment]
@jhardenberg @earnone We added this restriction and indeed you should only select the rcp experiment. We add the historical in the recipe ourselves, so when selecting rcp85 the recipe will use [historical, rcp85].

Removing historical from the dropdown list is technically difficult and we will not fix this for the demo.

**Comment by earnone** [comment]
@bpmweel  ok. Please update the default start-end years and normalization years as commented above: (1980-2020 start to end, 1980-1999 normalization period). 

@jhardenberg do we need a very quick process for the demo? I think we should keep 1980-2020 and one can simply modify the dates during the demo if needed.

**Comment by jhardenberg** [comment]
While multiple choice is not possible for the "Regions", there should be an additional option "All" which leads it to behave as if a list with all available regions has been selected. 
Can this be implemented in the WPS, or should we do it in ESMValTool ?

**Comment by jhardenberg** [comment]
BTW: This would be an idea also for the models: since HYINT is capable of producing plots for multiple models, there should be an option to select all available models in a class (e.g. all historical r1i1p1 models)

**Comment by jhardenberg** [comment]
> @jhardenberg @earnone We added this restriction and indeed you should only select the rcp experiment. We add the historical in the recipe ourselves, so when selecting rcp85 the recipe will use [historical, rcp85].
> 
> Removing historical from the dropdown list is technically difficult and we will not fix this for the demo.

I am still not sure that I understand: I may wish to use this diagnostic for the historical period (it is certainly possible in ESMValTool)...the WPS will not allow that ?  Or should I select RCP85 and then a range of years in the historical period? Does not seem very user friendly.
